run-app:
	npx ts-node app/app.ts

add-can-mint-multisig:
	npx ts-node app/admin/multisig/add_can_mint_with_multisig.ts


mint-to-user:
	npx ts-node app/admin/mint.ts

transfer-to-user:
	npx ts-node app/transfer.ts

token-initialize:
	npx ts-node migrations/deploy.ts

create-multisig:
	npx ts-node app/multisig.ts

burn-by-delegate:
	npx ts-node app/admin/burn_by_delegate.ts

make run-tests:
	anchor test
