add-can-mint:
	npx ts-node app/admin/add_can_mint.ts

add-can-mint-multisig:
	npx ts-node app/admin/multisig/add_can_mint_with_multisig.ts

set-mint-amount:
	npx ts-node app/admin/set_mint_amount.ts
mint-to-user:
	npx ts-node app/admin/mint.ts

transfer-to-user:
	npx ts-node app/transfer.ts

remove-mint-amount:
	npx ts-node app/admin/remove_mint_amount.ts

token-initialize:
	npx ts-node migrations/deploy.ts

create-multisig:
	npx ts-node app/multisig.ts

change-admin:
	npx ts-node app/admin/change_admin.ts

burn-by-delegate:
	npx ts-node app/admin/burn_by_delegate.ts

make run-tests:
	anchor test
