
build-contracts: 
	npx blueprint build

deploy-contracts: 
	npx blueprint run

run-tests:
	npx blueprint test

run-mint-tests:
	npx blueprint test tests/cngn-unit/mint.spec.ts

run-transfer-tests:
	npx blueprint test tests/cngn-unit/transfer.spec.ts

run-config-tests:
	npx blueprint test tests/cngn-unit/configAndSetup.spec.ts